---
name: Main Merge

on:
  push:
    branches: [main]
    paths-ignore:
    - .github/dependabot.yml
    - '*.md'
    - '*.yaml'
    - .gitignore
    - LICENSE
  pull_request:
    branches: [main]
    paths-ignore:
    - .github/dependabot.yml
    - '*.md'
    - '*.yaml'
    - .gitignore
    - LICENSE

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile
      id: hadolint

    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      id: shellcheck

  unittests:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y bash git kcov
      id: install-dependencies

    - name: Install Shellspec
      run: |
        cd /opt/
        sudo git clone https://github.com/shellspec/shellspec.git
        sudo ln -s /opt/shellspec/shellspec /usr/local/bin/shellspec
      id: install-shellspec

    - name: Run shellspec with kcov
      env:
        SHELLSPEC_KCOV_OPTS: "--include-pattern=*.sh"
      run: |
        shellspec -s bash --kcov

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/cobertura.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
